export const AUTH_SUCCESS = 'AUTH_SUCCESS';
export const AUTH_FAILURE = 'AUTH_FAILURE';
export const AUTH_LOGOUT = 'AUTH_LOGOUT';
export const REGISTER_SUCCESS = 'REGISTER_SUCCESS';
export const REGISTER_FAILURE = 'REGISTER_FAILURE';

export const CHARACTERS_REQUEST = 'CHARACTERS_REQUEST';
export const CHARACTERS_LOAD = 'CHARACTERS_LOAD';
export const SELECTED_PAGE_CHARACTERS = 'SELECTED_PAGE_CHARACTERS';
export const FAVORITE_CHARACTERS_LOCAL_STORAGE_LOAD = 'FAVORITE_CHARACTERS_LOCAL_STORAGE_LOAD';
export const ADD_CHARACTERS_TO_FAVORITE = 'ADD_CHARACTERS_TO_FAVORITE';
export const REMOVE_CHARACTERS_FROM_FAVORITE = 'REMOVE_CHARACTERS_FROM_FAVORITE';
export const FILTER_FAVORITE_CHARACTERS = 'FILTER_FAVORITE_CHARACTERS';
export const CHARACTERS_ERROR = 'CHARACTERS_ERROR';

export const LOCATIONS_REQUEST = 'LOCATIONS_REQUEST';
export const LOCATIONS_LOAD = 'LOCATIONS_LOAD';
export const FAVORITE_LOCATIONS_LOCAL_STORAGE_LOAD = 'FAVORITE_LOCATIONS_LOCAL_STORAGE_LOAD';
export const SELECTED_PAGE_LOCATIONS = 'SELECTED_PAGE_LOCATIONS';
export const ADD_LOCATIONS_TO_FAVORITE = 'ADD_LOCATIONS_TO_FAVORITE';
export const REMOVE_LOCATIONS_FROM_FAVORITE = 'REMOVE_LOCATIONS_FROM_FAVORITE';
export const FILTER_FAVORITE_LOCATIONS = 'FILTER_FAVORITE_LOCATIONS';
export const LOCATIONS_ERROR = 'LOCATIONS_ERROR';

export const EPISODES_REQUEST = 'EPISODES_REQUEST';
export const EPISODES_LOAD = 'EPISODES_LOAD';
export const FAVORITE_EPISODES_LOCAL_STORAGE_LOAD = 'FAVORITE_EPISODES_LOCAL_STORAGE_LOAD';
export const SELECTED_PAGE_EPISODES = 'SELECTED_PAGE_EPISODES';
export const ADD_EPISODES_TO_FAVORITE = 'ADD_EPISODES_TO_FAVORITE';
export const REMOVE_EPISODES_FROM_FAVORITE = 'REMOVE_EPISODES_FROM_FAVORITE';
export const FILTER_FAVORITE_EPISODES = 'FILTER_FAVORITE_EPISODES';
export const SET_EPISODES_CHARACTERS = 'SET_EPISODES_CHARACTERS';
export const EPISODES_ERROR = 'EPISODES_ERROR';

export const SET_QUANTITY_PAGES = 'SET_QUANTITY_PAGES';
